name: Android CI/CD

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v2
      continue-on-error: true
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 11076708
        packages: 'platform-tools platforms;android-35 build-tools;35.0.0'
      
    - name: Accept Android SDK Licenses
      run: yes | sdkmanager --licenses || true
      
    - name: Grant Execute Permission for Gradlew
      run: chmod +x gradlew
      
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: wrapper
        
    - name: Cache Gradle Dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.android/build-cache
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/gradle.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Create local.properties
      run: echo "sdk.dir=$ANDROID_HOME" > local.properties
          
    - name: Decode Keystore
      if: github.event_name != 'pull_request'
      env:
        ENCODED_STRING: ${{ secrets.KEYSTORE_BASE64 }}
      run: |
        if [ ! -z "$ENCODED_STRING" ]; then
          echo $ENCODED_STRING | base64 -di > keystore.jks
        fi
        
    - name: Clean Project
      run: ./gradlew clean --stacktrace
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        
    - name: Build Release APK
      if: github.event_name != 'pull_request'
      run: ./gradlew assembleRelease --stacktrace
      continue-on-error: true
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        
    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest --stacktrace
      continue-on-error: true
      
    - name: Run Lint Checks
      run: ./gradlew lintDebug --stacktrace
      continue-on-error: true
      
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/*.apk
        retention-days: 30
        if-no-files-found: warn
        
    - name: Upload Release APK
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/*.apk
        retention-days: 90
        if-no-files-found: ignore
        
    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports
        path: |
          app/build/reports/tests/
          app/build/reports/lint-results-*.html
        retention-days: 30
        if-no-files-found: ignore
        
    - name: Upload Build Logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-logs
        path: |
          app/build/outputs/logs/
          app/build/reports/
        retention-days: 7
        if-no-files-found: ignore
        
    - name: Cleanup Keystore
      if: always()
      run: rm -f keystore.jks
