name: Android CI/CD

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    strategy:
      matrix:
        api-level: [29, 33]
        
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
  api-level: 35
  build-tools: '35.0.0'
  packages: |
    platform-tools
    platforms;android-35
    build-tools;35.0.0
    cmdline-tools;latest
      
    - name: Grant Execute Permission for Gradlew
      run: chmod +x gradlew
      
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      continue-on-error: true
      with:
      gradle-version: 8.7
validate-wrappers: false
        gradle-version: wrapper
        
    - name: Cache Gradle Dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.android/build-cache
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/gradle.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Decode Keystore
      if: github.event_name != 'pull_request'
      env:
        ENCODED_STRING: ${{ secrets.KEYSTORE_BASE64 }}
      run: |
        if [ ! -z "$ENCODED_STRING" ]; then
          echo $ENCODED_STRING | base64 -di > keystore.jks
        fi
        
    - name: Clean Project
      run: ./gradle clean
      
    - name: Build Debug APK
      run: ./gradle assembleDebug --stacktrace --no-daemon
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        
    - name: Build Release APK
      if: github.event_name != 'pull_request'
      run: ./gradle assembleRelease --stacktrace --no-daemon
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        
    - name: Run Unit Tests
      run: ./gradle testDebugUnitTest --stacktrace
      
    - name: Run Lint Checks
      run: ./gradle lintDebug --stacktrace
      continue-on-error: true
      
    - name: Generate Test Report
      uses: dorny/test-reporter@v1
      continue-on-error: true
      if: always()
      with:
        name: Test Results
        path: '**/build/test-results/test*/*.xml'
        reporter: java-junit
        fail-on-error: false
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-${{ matrix.api-level }}
        path: app/build/outputs/apk/debug/*.apk
        retention-days: 30
        if-no-files-found: error
        
    - name: Upload Release APK
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: app-release-${{ matrix.api-level }}
        path: app/build/outputs/apk/release/*.apk
        retention-days: 90
        if-no-files-found: warn
        
    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports-${{ matrix.api-level }}
        path: |
          app/build/reports/tests/
          app/build/reports/lint-results-*.html
        retention-days: 30
        
    - name: Upload Build Outputs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-outputs-${{ matrix.api-level }}
        path: |
          app/build/outputs/logs/
          app/build/reports/
        retention-days: 7
        
    - name: Cleanup Keystore
      if: always()
      run: rm -f keystore.jks

